version: "2"
services:
  
  pwn:
    build:
      context: .
      dockerfile: Dockerfile
    image: ctftraining/huxiangbei_2019_pwn_namesystem
    volumes:
      - ./tcpdump:/var/lib/tcpdump
    ports:
      - "10001:10000"
    environment:
      - FLAG=ctftraining{welcome_to_ctftraining}
      - TCPDUMP_ENABLE=0
